apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: integration1687900965845
spec:
  flows:
    - from:
        uri: "timer:tick"
        steps:
          - set-body:
                simple: "${ref:myBean}"
          - to:
              uri: "log:info"
    - beans:
        - name: myBean
          type: org.apache.camel.model.FromDefinition
          properties:
            uri: foo