<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:param name="account"/>
    <xsl:param name="orderSequence"/>
    <xsl:template match="/">
        <ShipOrder xmlns="kaoto">
            <xsl:choose/>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>